"""adding a new column to review model

Revision ID: 0a30eeb56090
Revises: 164ce0f4c38d
Create Date: 2022-05-17 15:30:41.038192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a30eeb56090'
down_revision = '164ce0f4c38d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('listing_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'reviews', 'listings', ['listing_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'listing_id')
    # ### end Alembic commands ###
