"""empty message

Revision ID: 164ce0f4c38d
Revises: 9cd1d8e86b15
Create Date: 2022-05-16 08:57:45.593785

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '164ce0f4c38d'
down_revision = '9cd1d8e86b15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('is_purchased', sa.Boolean(), nullable=False))
    op.add_column('listings', sa.Column('buyer_id', sa.Integer(), nullable=True))
    op.alter_column('listings', 'photos',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'listings', 'users', ['buyer_id'], ['id'])
    if environment == "production":
        op.execute(f"ALTER TABLE <table_name> SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.alter_column('listings', 'photos',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('listings', 'buyer_id')
    op.drop_column('listings', 'is_purchased')
    # ### end Alembic commands ###
